In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'1.14.0'

In [5]:
const = tf.constant(10)

In [6]:
fill_mat = tf.fill((4, 4), 10)

In [7]:
myzeros = tf.zeros((4, 4))

In [8]:
myones = tf.ones((4, 4))

In [9]:
myrandn = tf.random_normal((4, 4), mean=0, stddev=1.0)

In [10]:
myrandu = tf.random_uniform((4, 4), minval=0, maxval=1)

In [11]:
my_ops = [const, fill_mat, myzeros, myones, myrandn, myrandu]

In [12]:
sess = tf.InteractiveSession()

In [13]:
for op in my_ops:
    print(sess.run(op))
    print("\n")

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[-0.16892186 -0.7865401   0.37228674 -0.6470378 ]
 [-0.8371424   1.2789863  -1.287962    0.09545314]
 [-0.08994209  0.7290699  -0.19684325  0.78611726]
 [-0.2601487   0.09011762  0.2405076  -0.28893238]]


[[0.3764044  0.7406286  0.9654716  0.69240534]
 [0.81070507 0.8758379  0.14733851 0.17916858]
 [0.60339    0.4815638  0.8951106  0.21102428]
 [0.6936414  0.21553254 0.08946896 0.6329683 ]]




In [14]:
a = tf.constant([[1,2], [3,4]])

In [15]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [16]:
b = tf.constant([[10], [100]])

In [17]:
result = tf.matmul(a, b)

In [18]:
sess.run(result)

array([[210],
       [430]], dtype=int32)

In [19]:
result.eval()

array([[210],
       [430]], dtype=int32)

In [20]:
n1 = tf.constant(1)

In [21]:
n2 = tf.constant(2)

In [22]:
n3 = n1 + n2

In [23]:
with tf.Session() as sess:
    result = sess.run(n1 + n2)

In [24]:
result

3