In [2]:
import numpy as np

In [3]:
my_list = [1, 2, 3]

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [8]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [9]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.linspace(3, 10, 100)

array([ 3.        ,  3.07070707,  3.14141414,  3.21212121,  3.28282828,
        3.35353535,  3.42424242,  3.49494949,  3.56565657,  3.63636364,
        3.70707071,  3.77777778,  3.84848485,  3.91919192,  3.98989899,
        4.06060606,  4.13131313,  4.2020202 ,  4.27272727,  4.34343434,
        4.41414141,  4.48484848,  4.55555556,  4.62626263,  4.6969697 ,
        4.76767677,  4.83838384,  4.90909091,  4.97979798,  5.05050505,
        5.12121212,  5.19191919,  5.26262626,  5.33333333,  5.4040404 ,
        5.47474747,  5.54545455,  5.61616162,  5.68686869,  5.75757576,
        5.82828283,  5.8989899 ,  5.96969697,  6.04040404,  6.11111111,
        6.18181818,  6.25252525,  6.32323232,  6.39393939,  6.46464646,
        6.53535354,  6.60606061,  6.67676768,  6.74747475,  6.81818182,
        6.88888889,  6.95959596,  7.03030303,  7.1010101 ,  7.17171717,
        7.24242424,  7.31313131,  7.38383838,  7.45454545,  7.52525253,
        7.5959596 ,  7.66666667,  7.73737374,  7.80808081,  7.87

In [18]:
np.random.randint(0, 10, (3,3))

array([[3, 8, 9],
       [3, 4, 2],
       [1, 9, 7]])

In [23]:
arr = np.random.randint(0, 100, 10)

In [24]:
arr

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [25]:
arr.max()

93

In [26]:
arr.min()

4

In [27]:
arr.argmax()

8

In [28]:
arr.argmin()

0

In [29]:
arr.reshape((2, 5))

array([[ 4, 63, 40, 60, 92],
       [64,  5, 12, 93, 40]])

In [30]:
mat = np.arange(0, 100).reshape(10, 10)

In [31]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [32]:
mat[0, 1]

1

In [33]:
mat[:, 0]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [34]:
mat[5, :]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [35]:
mat[0:3, 0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [36]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [37]:
my_filter = mat > 50

In [38]:
mat[my_filter]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [39]:
import pandas as pd

In [41]:
df = pd.read_csv('salaries.csv')

In [42]:
df 

Name  Salary  Age
0    John   50000   34
1   Sally  120000   45
2  Alyssa   80000   27

In [47]:
df[['Salary', 'Name']]

Salary    Name
0   50000    John
1  120000   Sally
2   80000  Alyssa

In [48]:
df['Salary'].max()

120000

In [49]:
df.describe()

Salary        Age
count       3.000000   3.000000
mean    83333.333333  35.333333
std     35118.845843   9.073772
min     50000.000000  27.000000
25%     65000.000000  30.500000
50%     80000.000000  34.000000
75%    100000.000000  39.500000
max    120000.000000  45.000000

In [51]:
myfilter = df['Salary'] > 50000

In [53]:
df[df['Salary'] > 50000]

Name  Salary  Age
1   Sally  120000   45
2  Alyssa   80000   27