In [1]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [2]:
data = np.random.randint(0, 100, (10, 2))

In [3]:
data

array([[68, 73],
       [68, 37],
       [25, 57],
       [58, 71],
       [50,  7],
       [61, 31],
       [34, 81],
       [89,  0],
       [12, 73],
       [78, 12]])

In [4]:
scaler_model = MinMaxScaler()

In [5]:
type(scaler_model)

sklearn.preprocessing.data.MinMaxScaler

In [6]:
scaler_model.fit(data)

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [7]:
scaler_model.transform(data)

array([[0.72727273, 0.90123457],
       [0.72727273, 0.45679012],
       [0.16883117, 0.7037037 ],
       [0.5974026 , 0.87654321],
       [0.49350649, 0.08641975],
       [0.63636364, 0.38271605],
       [0.28571429, 1.        ],
       [1.        , 0.        ],
       [0.        , 0.90123457],
       [0.85714286, 0.14814815]])

In [9]:
scaler_model.fit_transform(data)

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[0.72727273, 0.90123457],
       [0.72727273, 0.45679012],
       [0.16883117, 0.7037037 ],
       [0.5974026 , 0.87654321],
       [0.49350649, 0.08641975],
       [0.63636364, 0.38271605],
       [0.28571429, 1.        ],
       [1.        , 0.        ],
       [0.        , 0.90123457],
       [0.85714286, 0.14814815]])

In [10]:
import pandas as pd

In [11]:
mydata = np.random.randint(0, 101, (50, 4))

In [12]:
mydata

array([[ 51,   1,  24,  83],
       [ 91,  28,  77,  78],
       [ 91,  30,  38,  85],
       [ 41,  77,  13,   6],
       [  5,  61,   2,  32],
       [ 85,  17,  83,  25],
       [ 91,  98,  55,  64],
       [ 71,  43,  94,  10],
       [ 31,  66,  26,  87],
       [ 43, 100,  62,  90],
       [ 21,  30,  26,  19],
       [ 32,  85,  53,  48],
       [ 31,   9,  37,  46],
       [ 93,   7,  75,  28],
       [ 97,  71,  55,  96],
       [ 83,   6,  25,  56],
       [ 74,  78,  17,  77],
       [ 15,  52,  33,  72],
       [ 51,  91,  57,  28],
       [ 29,  41,  56, 100],
       [ 74,   1,  77,  36],
       [ 67,  31,  37,  73],
       [ 17,  56,  45,  10],
       [ 24,  59,  90,   4],
       [ 85,  61,  24,  89],
       [ 92,  95,  93,  67],
       [ 71,  71,   5,  84],
       [ 90,  83,  75,  72],
       [  5,  39,  15,  11],
       [ 49,  82,  30,  40],
       [ 93,  20,  71,  34],
       [ 72,  61, 100,  66],
       [ 21,  42,  70,  17],
       [ 97,  30,  27,  18],
       [ 96,  

In [18]:
df = pd.DataFrame(data=mydata, columns = ['f1', 'f2', 'f3', 'label'])

In [19]:
df

f1   f2   f3  label
0   51    1   24     83
1   91   28   77     78
2   91   30   38     85
3   41   77   13      6
4    5   61    2     32
5   85   17   83     25
6   91   98   55     64
7   71   43   94     10
8   31   66   26     87
9   43  100   62     90
10  21   30   26     19
11  32   85   53     48
12  31    9   37     46
13  93    7   75     28
14  97   71   55     96
15  83    6   25     56
16  74   78   17     77
17  15   52   33     72
18  51   91   57     28
19  29   41   56    100
20  74    1   77     36
21  67   31   37     73
22  17   56   45     10
23  24   59   90      4
24  85   61   24     89
25  92   95   93     67
26  71   71    5     84
27  90   83   75     72
28   5   39   15     11
29  49   82   30     40
30  93   20   71     34
31  72   61  100     66
32  21   42   70     17
33  97   30   27     18
34  96   55   66     69
35  99   32   68      2
36  69   16   64     60
37  93   39   85     88
38  42   35   20     86
39   1   31   33     28
40  53   33    5     26
41  97   10   84      1
42  27   84   73     26
43   3   22    0     73
44  31   26   44     98
45  82   24    2     15
46  54   10   62     15
47  56   34   93     99
48  99   83   12     87
49  60    8   29      2

In [20]:
X = df[['f1', 'f2', 'f3']]

In [21]:
X

f1   f2   f3
0   51    1   24
1   91   28   77
2   91   30   38
3   41   77   13
4    5   61    2
5   85   17   83
6   91   98   55
7   71   43   94
8   31   66   26
9   43  100   62
10  21   30   26
11  32   85   53
12  31    9   37
13  93    7   75
14  97   71   55
15  83    6   25
16  74   78   17
17  15   52   33
18  51   91   57
19  29   41   56
20  74    1   77
21  67   31   37
22  17   56   45
23  24   59   90
24  85   61   24
25  92   95   93
26  71   71    5
27  90   83   75
28   5   39   15
29  49   82   30
30  93   20   71
31  72   61  100
32  21   42   70
33  97   30   27
34  96   55   66
35  99   32   68
36  69   16   64
37  93   39   85
38  42   35   20
39   1   31   33
40  53   33    5
41  97   10   84
42  27   84   73
43   3   22    0
44  31   26   44
45  82   24    2
46  54   10   62
47  56   34   93
48  99   83   12
49  60    8   29

In [22]:
y = df['label']

In [23]:
y

0      83
1      78
2      85
3       6
4      32
5      25
6      64
7      10
8      87
9      90
10     19
11     48
12     46
13     28
14     96
15     56
16     77
17     72
18     28
19    100
20     36
21     73
22     10
23      4
24     89
25     67
26     84
27     72
28     11
29     40
30     34
31     66
32     17
33     18
34     69
35      2
36     60
37     88
38     86
39     28
40     26
41      1
42     26
43     73
44     98
45     15
46     15
47     99
48     87
49      2
Name: label, dtype: int32

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 101)

In [28]:
X_train.shape

(35, 3)

In [29]:
X_test.shape

(15, 3)